apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-xbjo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-xbjo
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-xbjo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-xbjo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-xbjo
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-daxp-tenant/rhtap-demo-app/hacbs-test-project-xbjo@sha256:0eda4923a8c092753c3163849bfb3302169f5844696e3ebca4c1b0683bfd3733
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
