apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-xbjo
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-daxp-tenant/rhtap-demo-app/hacbs-test-project-xbjo@sha256:0eda4923a8c092753c3163849bfb3302169f5844696e3ebca4c1b0683bfd3733
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
